### PR TITLE
New media pipeline

### PR DESCRIPTION
**Pull request by AThomsen**
Lots of changes here. Should really be multiple Pull requests but one change let to another. [Refactorman :-)](https://www.monkeyuser.com/assets/images/2017/56-refactor-man.png)

I've tested it on Arch Linux and shortly in Windows. The changes are quite substantial though, so please consider this unstable.

### CDG streaming file reader
Instead of reading all cdg images to memory on play start, the cdg data is now read ad-hoc and frames are fed to the pipeline ad-hoc.
Advantages:
* There is no additional memory usage when playing cdg files other than that the raw cdg-file is read to memory and of couse gsteramer queues.
* The old code was capped at 25 FPS probably to save memory. The new implementation does not need this, but still I capped it at 60 FPS to prevent flooding the pipeline.
A disadvantage is that the reader is forward only, so seeking to a previous position in the will cause the file to be read from the start. I don't believe this is noticeable though.

### Use a custom pipeline instead of *Playbin*
The old code used the Playbin element of gstreamer. This takes care of a lot of plumbing when playing normal media files. But there were some problems adding cdg files to this element.
The new code is using the Pipeline element and adding the needed elements to this. This means we can properly support cdg appsrc and should give some advantages later on.

### Remove Pitch plugin
... from *Bad* as there are some problems with a/v sync. Instead tweak scaleTempo to mimic SoundTouch behaviour. 
In my ears it sounds the same and re-enables seeking in cdg-files when tempo is != 100%.
From gstreamer 1.8 it is also possible to change playback rate without skipping in the audio. This works for video but for some reason not appsrc (cdg).  Needs more investigation.

### Clean up and refactoring
* Logic moved into separate files to implement some separation of concern.
* Renames for consistency.
* Duplicate code reduced.
* Some small bugs fixed. And probably introduced some as well :-)

While these changes are not strictly necessary I hope it makes the code easier to understand and make further development easier. Especially for new people :-)

## Future plans
With these changes done I propose another change: Use only one MediaBackend instance and use gstreamers audiomixer and videomixer elements to do actual transitions/fades between karaoke and background music/video.

### CODE REVIEW

**Comment by coyote1357** [comment]
Thanks for all of your work on this.  I'm hosting a show tonight, but I'll dig into it this week and get it merged and do some torture testing.

You're cleaning up a lot of the ugly that got introduced early on and has stuck around from when I was still very much in the beginning stages of teaching myself c++.

And I agree, would definitely be better to have a single backend for break and karaoke.  I've never been super happy with my hacky fader implementation.  Just need to make sure that we retain the option to not allow karaoke / break music overlap for people who use the recording feature.  Would also be nice to implement proper crossfading between break songs in the process, but would likely require having two sets of elements for an A and B break music "deck" and keeping track of which one is current.

**Comment by coyote1357** [comment]
Oh, and big lolz at refactorman haha

**Comment by AThomsen** [comment]
Yes, the torture. I had to comment that out as I'm not sure what it is suppose to test/prove when it's no longer rendering image frames to memory.

I haven't used the recording feature myself. How does it work? Are you simply recording from the selected audio device (plugged into FOH) OR microphone audio from device mixed with feed from gstreamer?

**Comment by AThomsen** [comment]
Just found a bug. EOS is not emitted when using software renderer. Will fix tomorrow :-)

**Comment by coyote1357** [comment]
Oh, the last draw command is just so that the silence detection doesn't inadvertently kill playback on a song that has a silent outro but still has lyrics the singer is supposed to be singing.  Added that in after having a few irate singers after their song stopped prematurely.

But for no overlap it just prevents the karaoke playback from starting until break music fades all the way out and prevents break music from starting until the karaoke track has stopped.

Recording lets you just select in input (in my case I use a USB audio interface that takes an XLR line level signal from my mixer), and then records every karaoke performance with the singer's name, artist, title, and timestamp.  Starts recording on karaoke song start, ends when the song ends or is stopped.

**Comment by coyote1357** [comment]
Getting back the last draw info wouldn't be too hard, I could just write a separate function that runs through the cdg file as if it would be processing it, but just basically do nothing aside from determine when the valid last draw command is.  Would probably only take a few ms to process a file that way and wouldn't have a perceptible memory or CPU usage hit since it wouldn't actually be doing any drawing or storing frames.

**Comment by AThomsen** [comment]
> Oh, the last draw command is just so that the silence detection....

Sorry - this is a reply to what?

**Comment by coyote1357** [comment]
You said you had to comment something out, I thought you were referring to the cdg last draw stuff from my implemention.

**Comment by AThomsen** [comment]
This closes #212.

**Pull request merged**
