### PR TITLE
2022refresh

### PR DESCRIPTION
**Pull request by AThomsen**

### CODE REVIEW

**Review by ILightburn — APPROVED** [review]
gstreamer 18.4 to 20.3, regex fix of not pulling proper song-id, use getsongidcapturegrp, instead of getsongidregex. looks good to me.

**Review by ILightburn — APPROVED** [review]
going from d3dvideosink to d3dllvideosink, fixes some issue or is needed for new gstreamer. i'm taking Anders' word for it. fine by me.

**Review by ILightburn — APPROVED** [review]
this fixes custom pattern dialog field order. looks good to me.

**Review by ILightburn — APPROVED** [review]
this is the individual piece that fixes song-id not correct when using custom regex patters. looks okay to me.

**Review by ILightburn — APPROVED** [review]
this is the individual piece that upgrades gstreamer from 18.4 to 20.3. looks okay to me.

**Review by ILightburn — APPROVED** [review]
for the Win build, this switches from using d3dvideosink to d3d11videosink. looks good.

**Comment by tnjman** [comment]
So, we still have to look into this:
LGTM analysis: C/C++ Failing after 441m — Analysis failed (could not build the base commit (da2adee))
Log: https://lgtm.com/projects/g/OpenKJ/OpenKJ/logs/rev/pr-2fdb39107ae2ca47130e9fbecf7541f44bd66417/lang:cpp/stage:Build%20merge_13b0e5ddfe5583fbbf40b693aa13f24026522abf

**Pull request merged**
